version: "3.9"
services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      # celery -A attendance-classifier worker --loglevel=INFO
    command: ["celery", "-A", "attendance-classifier", "worker", "-l", "info"]
    volumes:
      - ./:/app/
